pipeline {
  agent { label 'pico-build' }
  stages {
    stage('Start Docker Compose') {
      steps {
        sh 'docker compose up'
      }
    }
    stage('Run OpenOCD') {
      steps {
        sh '${OPENOCD_PATH} -s ${SCRIPTS_PATH} -f board/pico-debug.cfg -c "tcl_port disabled" -c "gdb_port disabled" -c "program \"cmake-build-debug/atcmd.elf\"" -c "reset" -c "shutdown"'
      }
    }
    stage('Run Robot Framework Tests') {
      steps {
        sh 'robot --variable COM_PORT:${COM_PORT} robot_tests/atcmd.robot'
        robot outputPath: '.', logFileName: 'log.html', outputFileName: 'output.xml', reportFileName: 'report.hml', passThreshold: 100, unstableThreshold: 75.0
      }
    }
  }
}
